# Введение. Полносвязные слои. Функции активации (ноутбук)

> Начнем осваивать библиотеку `PyTorch`.

## План ноутбука

1. Установка `PyTorch`
1. Введение в `PyTorch`
1. Полносвязные слои и функции активации в `PyTorch`
1. Градиентный спуск своими руками

## Установка `PyTorch`

Мы будем использовать библиотеку для глубинного обучения `PyTorch`, ее можно не устанавливать, можно пользоваться сайтами [Kaggle](kaggle.com) и [Google Colab](colab.research.google.com/) для обучения в облаке (или с учителем?).

Чтобы установить `PyTorch` локально себе на компьютер нужно ответить на два вопроса - какая у вас операционная система и есть ли у вас дискретная видеокарта (GPU) и если есть, то какого производителя. В зависимости от ваших ответов мы получаем три варианта по операционной системе - Linux, Mac и Windows; три варианта по дискретной видеокарте - нет видеокарты (доступен только центральный процессор CPU), есть видеокарта от Nvidia или есть видеокарта от AMD (это производитель именно чипа, конечный вендор может быть другой, например, ASUS, MSI, Palit). Работа с PyTorch с видеокартой от AMD это экзотика, которая выходит за рамки нашего курса, поэтому рассмотрим только варианты *нет видеокарты*/*есть видеокарта от Nvidia*.


Выберите на [сайте](https://pytorch.org/get-started/locally/) подходящие вам варианты операционной системы/видеокарты и скопируйте команду для установки. Разберем подробно самые популярные варианты установки:

### Установка в Linux ([поддерживаемые дистрибутивы](https://pytorch.org/get-started/locally/#supported-linux-distributions))

На линуксе будет работать поддержка `PyTorch` в любой конфигурации, что у вас нет видеокарты, что есть от Nvidia, что от AMD.

Пререквизит для работы с видеокартой от Nvidia - нужно поставить CUDA, это инструмент от компании Nvidia, который позволяет ускорять вычисления на их же ГПУ. Чтобы поставить себе на машину все правильно воспользуйтесь этим [гайдом](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) от Nvidia.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` для тех, у кого нет видеокарты.

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116` для тех, у кого есть видеокарта (либо другой `--extra-index-url`, смотрите на сайте PyTorch, в зависимости от версии CUDA).

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch` для тех, у кого нет видеокарты.

`conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge` для тех, у кого есть видеокарта (либо немного другая команда, в зависимости от версии CUDA).

### Установка в Windows

На винде будет работать поддержка `PyTorch` только для видеокарт от Nvidia и без видеокарт вообще.

Пререквизит для работы с видеокартой от Nvidia - нужно поставить CUDA, это инструмент от компании Nvidia, который позволяет ускорять вычисления на их же ГПУ. Чтобы поставить себе на машину все правильно воспользуйтесь этим [гайдом](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html) от Nvidia.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` для тех, у кого нет видеокарты.

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116` для тех, у кого есть видеокарта (либо другой `--extra-index-url`, смотрите на сайте PyTorch, в зависимости от версии CUDA).

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch` для тех, у кого нет видеокарты.

`conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge` для тех, у кого есть видеокарта (либо немного другая команда, в зависимости от версии CUDA).



### Установка на Mac

На маках есть пока что поддержка `PyTorch` только центрального процессора, чуть позже появится поддержка ускорения на чипах M1, M2, M1 Pro и так далее.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu`

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch`

In [ ]:
!nvidia-smi

Fri Oct 11 11:54:25 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Введение в `PyTorch`

### Тензоры

Тензоры — это специализированная структура данных, по сути это массивы и матрицы. Тензоры очень похожи на массивы в numpy, так что, если у вас хорошо с numpy, то разобраться в PyTorch тензорах будет очень просто. В PyTorch мы используем тензоры для кодирования входных и выходных данных модели, а также параметров модели.

In [ ]:
import torch
import numpy as np

### Создание тензоров

Тензор можно создать напрямую из каких-то данных - нам подходят все списки с числами:

In [ ]:
some_data = [1, 2, 3, 4]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([1, 2, 3, 4])

In [ ]:
some_data = [[1, 2], [3, 4], [5, 6]]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
some_data = [[[1], [2]], [[3], [4]], [[5], [6]]]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

На самом деле про "все" списки с числами - обман. Если у вашего списка есть какой-то уровень вложенности, то должны совпадать размерности у всех вложенных списков (подробнее про размерности поговорим позже):

In [ ]:
some_other_data = [[1, 2], [3, 4], [5, 6, 7]]
some_other_tensor = torch.tensor(some_other_data)

some_other_tensor

ValueError: expected sequence of length 2 at dim 1 (got 3)

Также тензоры можно создавать из numpy массивов и наоборот:

In [ ]:
some_numpy_array = np.array(some_data)

some_numpy_array

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [ ]:
some_tensor_from_numpy = torch.from_numpy(some_numpy_array)

some_tensor_from_numpy

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

При этом если мы создаем тензор из numpy массива с помощью `torch.from_numpy`, то они делят между собой память, где лежат их данные и, соответственно, при изменении тензора меняется numpy массив и наоборот:

In [ ]:
x = np.ones(10)
y = torch.from_numpy(x)

x, y

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64))

In [ ]:
x += 1

x, y

(array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64))

In [ ]:
x = torch.ones(10)
y = x.numpy()

x, y

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
x += 1

x, y

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32))

Можем создать тензор со случайными или константными значениями:

In [ ]:
shape = (2, 3)

random_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
empty_tensor = torch.empty(shape)

random_tensor, ones_tensor, zeros_tensor, empty_tensor

(tensor([[0.3476, 0.1443, 0.6423],
         [0.3520, 0.5589, 0.7302]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1.0836e-02, 4.4006e-41, 2.5996e+15],
         [4.4006e-41, 2.9153e+15, 4.4006e-41]]))

In [ ]:
torch.diag(torch.tensor([1, 2, 3]))

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

Теперь поговорим про размерности подробнее.

У тензора есть какой-то размер, какая форма. Первое с чем нужно определиться, какой **размерности** тензор - количество осей у него.

In [ ]:
shape = (10)  # одна ось (вектор)

tensor = torch.rand(shape)

tensor

tensor([0.0814, 0.8316, 0.1099, 0.4443, 0.6024, 0.7133, 0.2662, 0.1936, 0.9720,
        0.3112])

In [ ]:
shape = (2, 3)  # две оси (матрица)

tensor = torch.rand(shape)

tensor

tensor([[0.9352, 0.1408, 0.6111],
        [0.9245, 0.7646, 0.8034]])

In [ ]:
shape = (3, 2, 3)  # три оси (и больше - тензор)

tensor = torch.rand(shape)

tensor

tensor([[[0.7887, 0.5876, 0.4240],
         [0.1750, 0.0792, 0.7602]],

        [[0.1177, 0.6588, 0.8218],
         [0.1111, 0.1567, 0.4593]],

        [[0.8135, 0.5024, 0.0441],
         [0.2041, 0.1507, 0.7094]]])

Тензор с размерностью 1 - это просто вектор, список чисел.

Тензор с размерностью 2 - это просто матрица, то есть список списков чисел.

Тензор с размерностью 3 и больше - это тензор, то есть список списков списков ... чисел.

Получить доступ к размеру уже созданного тензора - метод `.shape`:

In [ ]:
some_data = [[[1], [2]], [[3], [4]], [[5], [6]]]
some_tensor = torch.tensor(some_data)

print(some_tensor)
print(some_tensor.shape)

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])
torch.Size([3, 2, 1])


In [ ]:
torch.ones((3, 2, 1)).shape

torch.Size([3, 2, 1])

На первом семинаре по мо мы говорили про изображения, давайте сделаем тензор, который будет нам имитировать изображение - сделаем его размер `(c, h, w)`, где `h` и `w` это его высота и ширина, а `c` - число каналов в цветовом пространстве (в черно-белом 1, в RGB 3):

In [ ]:
h = 9
w = 16
c = 3

shape = (c, h, w)

image_tensor = torch.rand(shape)

image_tensor

tensor([[[0.4102, 0.4316, 0.1035, 0.5031, 0.4807, 0.2536, 0.1222, 0.9907,
          0.9831, 0.6375, 0.9189, 0.4953, 0.5582, 0.1030, 0.1950, 0.4638],
         [0.5373, 0.1434, 0.6391, 0.6647, 0.9363, 0.5209, 0.2212, 0.8658,
          0.3959, 0.2043, 0.7790, 0.9134, 0.1412, 0.5286, 0.5976, 0.0015],
         [0.3705, 0.2382, 0.6942, 0.1810, 0.8528, 0.6695, 0.4474, 0.3367,
          0.6757, 0.6056, 0.3951, 0.8060, 0.0380, 0.9960, 0.4804, 0.3763],
         [0.0381, 0.3043, 0.7316, 0.3893, 0.5197, 0.4528, 0.7058, 0.4919,
          0.3310, 0.0027, 0.8103, 0.4324, 0.2389, 0.7983, 0.5823, 0.3650],
         [0.0437, 0.0011, 0.3975, 0.9608, 0.3171, 0.7906, 0.9486, 0.2325,
          0.4345, 0.8515, 0.7648, 0.2247, 0.2396, 0.4718, 0.6554, 0.0492],
         [0.4021, 0.3153, 0.9716, 0.6400, 0.9949, 0.1779, 0.7154, 0.9456,
          0.3104, 0.7317, 0.4219, 0.8836, 0.8963, 0.9631, 0.3220, 0.5747],
         [0.8114, 0.4475, 0.8301, 0.3995, 0.9448, 0.3831, 0.9151, 0.4809,
          0.6381, 0.6917, 0.4773

In [ ]:
image_tensor.shape

torch.Size([3, 9, 16])

Можем попробовать поменять размер тензора, например, [вытянуть его в вектор](https://pytorch.org/docs/stable/generated/torch.ravel.html):

In [ ]:
image_tensor.ravel()

tensor([0.4102, 0.4316, 0.1035, 0.5031, 0.4807, 0.2536, 0.1222, 0.9907, 0.9831,
        0.6375, 0.9189, 0.4953, 0.5582, 0.1030, 0.1950, 0.4638, 0.5373, 0.1434,
        0.6391, 0.6647, 0.9363, 0.5209, 0.2212, 0.8658, 0.3959, 0.2043, 0.7790,
        0.9134, 0.1412, 0.5286, 0.5976, 0.0015, 0.3705, 0.2382, 0.6942, 0.1810,
        0.8528, 0.6695, 0.4474, 0.3367, 0.6757, 0.6056, 0.3951, 0.8060, 0.0380,
        0.9960, 0.4804, 0.3763, 0.0381, 0.3043, 0.7316, 0.3893, 0.5197, 0.4528,
        0.7058, 0.4919, 0.3310, 0.0027, 0.8103, 0.4324, 0.2389, 0.7983, 0.5823,
        0.3650, 0.0437, 0.0011, 0.3975, 0.9608, 0.3171, 0.7906, 0.9486, 0.2325,
        0.4345, 0.8515, 0.7648, 0.2247, 0.2396, 0.4718, 0.6554, 0.0492, 0.4021,
        0.3153, 0.9716, 0.6400, 0.9949, 0.1779, 0.7154, 0.9456, 0.3104, 0.7317,
        0.4219, 0.8836, 0.8963, 0.9631, 0.3220, 0.5747, 0.8114, 0.4475, 0.8301,
        0.3995, 0.9448, 0.3831, 0.9151, 0.4809, 0.6381, 0.6917, 0.4773, 0.3592,
        0.9358, 0.5976, 0.3763, 0.0698, 

In [ ]:
image_tensor.ravel().shape

torch.Size([432])

In [ ]:
h * w * c

432

Посчитаем количество элементов в тензоре с помощью [специальной функции](https://pytorch.org/docs/stable/generated/torch.numel.html):

In [ ]:
image_tensor.numel()

432

In [ ]:
h = 2
w = 3
c = 3

shape = (c, h, w)

image_tensor = torch.rand(shape)

image_tensor

tensor([[[0.8637, 0.4086, 0.8904],
         [0.3685, 0.2630, 0.7194]],

        [[0.8481, 0.2656, 0.6502],
         [0.0051, 0.3300, 0.2613]],

        [[0.9624, 0.7924, 0.5888],
         [0.4858, 0.6807, 0.4485]]])

Попробуем поменять размер с помощью функции [reshape](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape):

In [ ]:
image_tensor.reshape(c, h * w).shape

torch.Size([3, 6])

Попробуем собрать из нескольких тензоров один большой:

[torch.cat](https://pytorch.org/docs/stable/generated/torch.cat.html#torch.cat)

In [ ]:
x = torch.randn(2, 3)

In [ ]:
x

tensor([[-0.6054,  0.3005, -1.0850],
        [-2.2527,  0.9776, -0.7729]])

In [ ]:
torch.cat((x, x, x), dim=0)

tensor([[-0.6054,  0.3005, -1.0850],
        [-2.2527,  0.9776, -0.7729],
        [-0.6054,  0.3005, -1.0850],
        [-2.2527,  0.9776, -0.7729],
        [-0.6054,  0.3005, -1.0850],
        [-2.2527,  0.9776, -0.7729]])

In [ ]:
torch.cat((x, x, x), dim=1)

tensor([[-0.6054,  0.3005, -1.0850, -0.6054,  0.3005, -1.0850, -0.6054,  0.3005,
         -1.0850],
        [-2.2527,  0.9776, -0.7729, -2.2527,  0.9776, -0.7729, -2.2527,  0.9776,
         -0.7729]])

In [ ]:
x = torch.randn(3, 3)
y = torch.randn(5, 3)
z = torch.randn(1, 3)

for tensor in [x, y, z]:
    print(tensor)

torch.cat((x, y, z), dim=0)

tensor([[-1.3498, -0.4070,  0.5927],
        [ 0.4969,  0.1851,  0.7220],
        [ 0.8047, -2.5189,  0.6444]])
tensor([[ 2.3784, -1.3463, -0.2447],
        [-0.0453,  1.5249,  1.5086],
        [-0.2221,  0.0574, -1.0960],
        [-0.2103,  0.6082,  0.9466],
        [ 0.2263, -2.1937, -0.4378]])
tensor([[ 0.5228, -0.8025, -1.0040]])


tensor([[-1.3498, -0.4070,  0.5927],
        [ 0.4969,  0.1851,  0.7220],
        [ 0.8047, -2.5189,  0.6444],
        [ 2.3784, -1.3463, -0.2447],
        [-0.0453,  1.5249,  1.5086],
        [-0.2221,  0.0574, -1.0960],
        [-0.2103,  0.6082,  0.9466],
        [ 0.2263, -2.1937, -0.4378],
        [ 0.5228, -0.8025, -1.0040]])

In [ ]:
x = torch.randn(2, 3)
y = torch.randn(2, 5)
z = torch.randn(2, 1)

for tensor in [x, y, z]:
    print(tensor)

torch.cat((x, y, z), dim=1)

tensor([[-2.9909,  1.3393,  0.9201],
        [ 0.2128,  0.7635, -1.0643]])
tensor([[ 9.4922e-01, -1.4118e+00,  1.6400e+00,  9.2785e-04,  6.6651e-01],
        [ 3.3627e-01, -1.5545e+00, -9.4103e-01,  1.5928e+00, -5.2725e-01]])
tensor([[0.3174],
        [0.0757]])


tensor([[-2.9909e+00,  1.3393e+00,  9.2014e-01,  9.4922e-01, -1.4118e+00,
          1.6400e+00,  9.2785e-04,  6.6651e-01,  3.1744e-01],
        [ 2.1279e-01,  7.6349e-01, -1.0643e+00,  3.3627e-01, -1.5545e+00,
         -9.4103e-01,  1.5928e+00, -5.2725e-01,  7.5675e-02]])

Теперь добавим дополнительную ось:

[torch.unsqueeze](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html)

In [ ]:
x = torch.rand(2, 3)

print(x)
print()
print(x.unsqueeze(0), x.unsqueeze(0).shape)
print()
print(x.unsqueeze(1), x.unsqueeze(1).shape)
print()
print(x.unsqueeze(2), x.unsqueeze(2).shape)
print()
print(x.unsqueeze(2), x.unsqueeze(-1).shape)

tensor([[0.3673, 0.4733, 0.6131],
        [0.6649, 0.3623, 0.5753]])

tensor([[[0.3673, 0.4733, 0.6131],
         [0.6649, 0.3623, 0.5753]]]) torch.Size([1, 2, 3])

tensor([[[0.3673, 0.4733, 0.6131]],

        [[0.6649, 0.3623, 0.5753]]]) torch.Size([2, 1, 3])

tensor([[[0.3673],
         [0.4733],
         [0.6131]],

        [[0.6649],
         [0.3623],
         [0.5753]]]) torch.Size([2, 3, 1])

tensor([[[0.3673],
         [0.4733],
         [0.6131]],

        [[0.6649],
         [0.3623],
         [0.5753]]]) torch.Size([2, 3, 1])


Уберем лишние оси (где размер единичка):

In [ ]:
x = torch.rand(1, 2, 1, 3)

print(x)
print()
print(x.squeeze(), x.squeeze().shape)
print()
print(x.squeeze(0), x.squeeze(0).shape)

tensor([[[[0.4113, 0.5054, 0.5575]],

         [[0.5784, 0.6857, 0.7007]]]])

tensor([[0.4113, 0.5054, 0.5575],
        [0.5784, 0.6857, 0.7007]]) torch.Size([2, 3])

tensor([[[0.4113, 0.5054, 0.5575]],

        [[0.5784, 0.6857, 0.7007]]]) torch.Size([2, 1, 3])


Теперь поговорим про типы данных в тензорах. По умолчанию в тензорах лежат числа в torch.float32 для вещественных и torch.int64 для целочисленных.

In [ ]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9])

tensor

tensor([1.5000, 2.2000, 3.7000, 4.9000])

In [ ]:
tensor.dtype

torch.float32

In [ ]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.float16)

tensor

tensor([1.5000, 2.1992, 3.6992, 4.8984], dtype=torch.float16)

In [ ]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.bfloat16)

tensor

tensor([1.5000, 2.2031, 3.7031, 4.9062], dtype=torch.bfloat16)

In [ ]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.float64)

tensor

tensor([1.5000, 2.2000, 3.7000, 4.9000], dtype=torch.float64)

In [ ]:
tensor = torch.tensor([15, 22, 37, 49])

tensor

tensor([15, 22, 37, 49])

In [ ]:
tensor.dtype

torch.int64

In [ ]:
tensor = torch.tensor([15, 22, 37, 49], dtype=torch.int32)

tensor

tensor([15, 22, 37, 49], dtype=torch.int32)

In [ ]:
tensor = torch.tensor([15, 22, 37, 49], dtype=torch.int16)

tensor

tensor([15, 22, 37, 49], dtype=torch.int16)

Размещение тензора на GPU:

In [ ]:
# !nvidia-smi

In [ ]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_name())

True
Tesla T4


In [ ]:
!nvidia-smi

Fri Oct 11 12:12:57 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

print(device)

cuda:0


In [ ]:
tensor = torch.tensor([15, 22, 37, 49], device=device)

tensor

tensor([15, 22, 37, 49], device='cuda:0')

In [ ]:
tensor = torch.tensor([15, 22, 37, 49])

print(tensor)

tensor = tensor.to(device)

tensor

tensor([15, 22, 37, 49])


tensor([15, 22, 37, 49], device='cuda:0')

In [ ]:
tensor.to(torch.int32)

tensor([15, 22, 37, 49], device='cuda:0', dtype=torch.int32)

In [ ]:
tensor = tensor.cpu()

tensor

tensor([15, 22, 37, 49])

In [ ]:
tensor.cuda()

tensor([15, 22, 37, 49], device='cuda:0')

In [ ]:
tensor.device

device(type='cpu')

In [ ]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

a + b

tensor([[1.7276, 0.7917, 1.6986],
        [1.5158, 1.8346, 0.9102]])

In [ ]:
a = a.to(device)

a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [ ]:
b = b.to(device)

a + b

tensor([[1.7276, 0.7917, 1.6986],
        [1.5158, 1.8346, 0.9102]], device='cuda:0')

### Операции с тензорами

Большая часть операций с тензорами хорошо описана в их [документации](https://pytorch.org/docs/stable/torch.html), разберем основные:

In [ ]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

a, b

(tensor([[0.2359, 0.8428, 0.0995],
         [0.5348, 0.1808, 0.8686]]),
 tensor([[0.7052, 0.6897, 0.3297],
         [0.2659, 0.0599, 0.7602]]))

In [ ]:
# поэлементные

print(a + b)

print()

print(torch.add(a, b))

print()

print(a.add(b))

tensor([[0.9411, 1.5325, 0.4292],
        [0.8007, 0.2407, 1.6288]])

tensor([[0.9411, 1.5325, 0.4292],
        [0.8007, 0.2407, 1.6288]])

tensor([[0.9411, 1.5325, 0.4292],
        [0.8007, 0.2407, 1.6288]])


In [ ]:
print(a - b)

print()

print(torch.sub(a, b))

print()

print(a.sub(b))

tensor([[-0.4693,  0.1531, -0.2302],
        [ 0.2689,  0.1208,  0.1084]])

tensor([[-0.4693,  0.1531, -0.2302],
        [ 0.2689,  0.1208,  0.1084]])

tensor([[-0.4693,  0.1531, -0.2302],
        [ 0.2689,  0.1208,  0.1084]])


In [ ]:
print(a * b)

print()

print(torch.mul(a, b))

print()

print(a.mul(b))

tensor([[0.1663, 0.5813, 0.0328],
        [0.1422, 0.0108, 0.6603]])

tensor([[0.1663, 0.5813, 0.0328],
        [0.1422, 0.0108, 0.6603]])

tensor([[0.1663, 0.5813, 0.0328],
        [0.1422, 0.0108, 0.6603]])


In [ ]:
print(a / b)

print()

print(torch.div(a, b))

print()

print(a.div(b))

tensor([[0.3345, 1.2220, 0.3017],
        [2.0112, 3.0159, 1.1427]])

tensor([[0.3345, 1.2220, 0.3017],
        [2.0112, 3.0159, 1.1427]])

tensor([[0.3345, 1.2220, 0.3017],
        [2.0112, 3.0159, 1.1427]])


In [ ]:
a = torch.rand(2, 3)
b = torch.rand(3, 4)
c = torch.rand(5, 5)

a, b, c

(tensor([[0.9667, 0.6471, 0.5515],
         [0.6789, 0.6109, 0.5120]]),
 tensor([[0.2651, 0.4568, 0.1443, 0.6677],
         [0.1041, 0.4739, 0.2217, 0.4756],
         [0.3478, 0.3334, 0.0909, 0.2737]]),
 tensor([[0.8314, 0.1834, 0.5371, 0.5371, 0.0495],
         [0.7669, 0.4838, 0.2628, 0.7508, 0.6676],
         [0.3849, 0.0349, 0.3328, 0.6817, 0.7969],
         [0.5371, 0.9065, 0.9497, 0.1070, 0.5975],
         [0.2283, 0.2732, 0.5781, 0.7928, 0.2078]]))

In [ ]:
# матричные операции

print(a @ b, (a @ b).shape)

print()

print(torch.matmul(a, b), torch.matmul(a, b).shape)

print()

print(c.trace())

print()

print(c.exp())

tensor([[0.5155, 0.9321, 0.3331, 1.1043],
        [0.4216, 0.7703, 0.2799, 0.8840]]) torch.Size([2, 4])

tensor([[0.5155, 0.9321, 0.3331, 1.1043],
        [0.4216, 0.7703, 0.2799, 0.8840]]) torch.Size([2, 4])

tensor(1.9628)

tensor([[2.2965, 1.2013, 1.7110, 1.7110, 1.0507],
        [2.1532, 1.6222, 1.3005, 2.1186, 1.9495],
        [1.4695, 1.0355, 1.3949, 1.9772, 2.2186],
        [1.7110, 2.4758, 2.5849, 1.1129, 1.8175],
        [1.2565, 1.3142, 1.7827, 2.2095, 1.2310]])


### [Автоматическое дифференцирование](https://pytorch.org/docs/stable/notes/autograd.html)

In [ ]:
x = torch.rand(5)

x

tensor([0.7258, 0.5286, 0.7033, 0.3374, 0.1147])

In [ ]:
w = torch.rand(3, 5, requires_grad=True)

w

tensor([[0.9531, 0.8511, 0.7448, 0.3935, 0.0687],
        [0.9432, 0.2360, 0.2619, 0.2912, 0.2784],
        [0.5320, 0.3608, 0.7615, 0.0169, 0.1625]], requires_grad=True)

In [ ]:
print(w.grad)

None


In [ ]:
first_z = torch.empty(3)

first_z

tensor([4.5890e+15, 4.4006e-41, 2.9558e-33])

In [ ]:
for i in range(3):
    first_z[i] = torch.sum(w[i] * x)

first_z

tensor([1.8061, 1.1237, 1.1367], grad_fn=<CopySlices>)

In [ ]:
z = torch.matmul(x, w.t())

z

tensor([1.8061, 1.1237, 1.1367], grad_fn=<SqueezeBackward4>)

In [ ]:
v = torch.rand(3, requires_grad=True)

v

tensor([0.0682, 0.0917, 0.1555], requires_grad=True)

In [ ]:
print(v.grad)

None


In [ ]:
y = torch.sum(z * v)

y

tensor(0.4030, grad_fn=<SumBackward0>)

In [ ]:
y.item()

0.40304234623908997

In [ ]:
loss = torch.mean((y - 2) ** 2)

In [ ]:
loss

tensor(2.5503, grad_fn=<MeanBackward0>)

In [ ]:
print(f'{x.grad=}\n')
print(f'{w.grad=}\n')
print(f'{z=}\n')
print(f'{v.grad=}\n')

x.grad=None

w.grad=None

z=tensor([1.8061, 1.1237, 1.1367], grad_fn=<SqueezeBackward4>)

v.grad=None



In [ ]:
loss.backward()

In [ ]:
print(f'{x.grad=}\n')
print(f'{w.grad=}\n')
print(f'{z.grad=}\n')
print(f'{v.grad=}\n')

x.grad=None

w.grad=tensor([[-0.1581, -0.1151, -0.1531, -0.0735, -0.0250],
        [-0.2127, -0.1549, -0.2061, -0.0989, -0.0336],
        [-0.3606, -0.2626, -0.3494, -0.1676, -0.0570]])

z.grad=None

v.grad=tensor([-5.7684, -3.5891, -3.6306])



<ipython-input-86-b1828bd1c118>:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(f'{z.grad=}\n')


In [ ]:
a = torch.rand(1, requires_grad=True)
b = torch.rand(1, requires_grad=True)

a, b

(tensor([0.9873], requires_grad=True), tensor([0.7470], requires_grad=True))

In [ ]:
loss = (a - b)

loss

tensor([0.2404], grad_fn=<SubBackward0>)

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [ ]:
loss.backward()

In [ ]:
print(f'{a.grad=}\n')  # 1
print(f'{b.grad=}\n')  # -1

a.grad=tensor([1.])

b.grad=tensor([-1.])



In [ ]:
a.grad.zero_()
b.grad.zero_()

tensor([0.])

In [ ]:
loss = (a - b) ** 2

loss

tensor([0.0578], grad_fn=<PowBackward0>)

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=tensor([0.])

b.grad=tensor([0.])



In [ ]:
loss.backward()

In [ ]:
print(f'{a.grad=}\n')  # 2 * (a - b)
print(f'{b.grad=}\n')  # -2 * (a - b)

a.grad=tensor([0.4807])

b.grad=tensor([-0.4807])



In [ ]:
2 * (a - b)

tensor([0.4807], grad_fn=<MulBackward0>)

In [ ]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.6391, 0.9885, 0.7630, 0.2066, 0.0315],
         [0.2761, 0.2394, 0.0535, 0.9663, 0.7648],
         [0.7110, 0.1037, 0.6037, 0.4254, 0.2018]], requires_grad=True),
 tensor([[0.1178, 0.1721, 0.5752, 0.0850, 0.1024],
         [0.6021, 0.1464, 0.9100, 0.5058, 0.7572],
         [0.0579, 0.2390, 0.6975, 0.2550, 0.2330]], requires_grad=True))

In [ ]:
loss = torch.mean(a * b)

loss

tensor(0.1777, grad_fn=<MeanBackward0>)

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [ ]:
loss.backward()

In [ ]:
print(f'{a.grad=}\n')  # b / (3 * 5)
print(f'{b.grad=}\n')  # a / (3 * 5)

a.grad=tensor([[0.0079, 0.0115, 0.0383, 0.0057, 0.0068],
        [0.0401, 0.0098, 0.0607, 0.0337, 0.0505],
        [0.0039, 0.0159, 0.0465, 0.0170, 0.0155]])

b.grad=tensor([[0.0426, 0.0659, 0.0509, 0.0138, 0.0021],
        [0.0184, 0.0160, 0.0036, 0.0644, 0.0510],
        [0.0474, 0.0069, 0.0402, 0.0284, 0.0135]])



In [ ]:
a / 15

tensor([[0.0426, 0.0659, 0.0509, 0.0138, 0.0021],
        [0.0184, 0.0160, 0.0036, 0.0644, 0.0510],
        [0.0474, 0.0069, 0.0402, 0.0284, 0.0135]], grad_fn=<DivBackward0>)

In [ ]:
b / 15

tensor([[0.0079, 0.0115, 0.0383, 0.0057, 0.0068],
        [0.0401, 0.0098, 0.0607, 0.0337, 0.0505],
        [0.0039, 0.0159, 0.0465, 0.0170, 0.0155]], grad_fn=<DivBackward0>)

In [ ]:
a = torch.rand(3, 5, requires_grad=True)

print(f'{a=}\n')

loss1 = torch.sum(a ** 2) # 2a
loss2 = torch.sum(a) # 1

print(f'{a.grad=}\n')

loss1.backward()

print(f'{a.grad=}\n')

loss2.backward()

print(f'{a.grad=}\n')

a=tensor([[0.0592, 0.0030, 0.9880, 0.5481, 0.8270],
        [0.4287, 0.5934, 0.2948, 0.1465, 0.3260],
        [0.7453, 0.6363, 0.3021, 0.0054, 0.1105]], requires_grad=True)

a.grad=None

a.grad=tensor([[0.1184, 0.0060, 1.9760, 1.0961, 1.6540],
        [0.8574, 1.1868, 0.5897, 0.2929, 0.6519],
        [1.4906, 1.2726, 0.6042, 0.0107, 0.2210]])

a.grad=tensor([[1.1184, 1.0060, 2.9760, 2.0961, 2.6540],
        [1.8574, 2.1868, 1.5897, 1.2929, 1.6519],
        [2.4906, 2.2726, 1.6042, 1.0107, 1.2210]])



In [ ]:
print(f'{2*a=}\n')
print(f'{2*a+1=}')

2*a=tensor([[0.1184, 0.0060, 1.9760, 1.0961, 1.6540],
        [0.8574, 1.1868, 0.5897, 0.2929, 0.6519],
        [1.4906, 1.2726, 0.6042, 0.0107, 0.2210]], grad_fn=<MulBackward0>)

2*a+1=tensor([[1.1184, 1.0060, 2.9760, 2.0961, 2.6540],
        [1.8574, 2.1868, 1.5897, 1.2929, 1.6519],
        [2.4906, 2.2726, 1.6042, 1.0107, 1.2210]], grad_fn=<AddBackward0>)


In [ ]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=False)

a, b

(tensor([[0.0351, 0.9216, 0.4761, 0.1819, 0.7945],
         [0.6458, 0.9624, 0.5655, 0.6882, 0.9046],
         [0.5619, 0.0658, 0.6451, 0.8772, 0.1969]], requires_grad=True),
 tensor([[0.6509, 0.4312, 0.2947, 0.9468, 0.1166],
         [0.9730, 0.9398, 0.9161, 0.3051, 0.6559],
         [0.4403, 0.6894, 0.7562, 0.0351, 0.1687]]))

In [ ]:
loss = torch.sum(a - b)

loss

tensor(0.2030, grad_fn=<SumBackward0>)

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [ ]:
loss.backward()

In [ ]:
print(f'{a.grad=}\n')  # all ones
print(f'{b.grad=}\n')  # None

a.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

b.grad=None



In [ ]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.1821, 0.1378, 0.2673, 0.6408, 0.0896],
         [0.5470, 0.0858, 0.4976, 0.6565, 0.4641],
         [0.4266, 0.7914, 0.1246, 0.6686, 0.6741]], requires_grad=True),
 tensor([[0.0557, 0.4916, 0.0344, 0.5987, 0.1312],
         [0.0616, 0.5124, 0.4772, 0.1971, 0.5381],
         [0.1897, 0.3603, 0.0474, 0.8344, 0.1375]], requires_grad=True))

In [ ]:
with torch.no_grad():
    loss = torch.sum(a - b)

loss

tensor(1.5865)

In [ ]:
loss = torch.sum(a - b)
loss

tensor(1.5865, grad_fn=<SumBackward0>)

In [ ]:
loss

tensor(1.5865)

In [ ]:
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.0055, 0.7428, 0.9647, 0.8440, 0.8663],
         [0.1319, 0.0118, 0.3571, 0.6656, 0.2885],
         [0.0360, 0.3297, 0.4886, 0.5197, 0.9239]], requires_grad=True),
 tensor([[0.7665, 0.6934, 0.3406, 0.7668, 0.1723],
         [0.1563, 0.8038, 0.6596, 0.0198, 0.0882],
         [0.7812, 0.8875, 0.8367, 0.0127, 0.3514]], requires_grad=True))

In [ ]:
with torch.inference_mode():
    loss = torch.sum(a - b)

loss

tensor(-0.1607)

In [ ]:
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
with torch.no_grad():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)

    loss = torch.sum(a + b)

    print(f'{loss=}')

    loss.backward()

loss=tensor(16.0471)


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
a

tensor([[0.8366, 0.2279, 0.8344, 0.4948, 0.0671],
        [0.9482, 0.7104, 0.8506, 0.5168, 0.8806],
        [0.9880, 0.0597, 0.5755, 0.1203, 0.9650]], requires_grad=True)

In [ ]:
loss2 = torch.sum(a + b)

loss2

tensor(16.0471, grad_fn=<SumBackward0>)

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [ ]:
loss2.backward()

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

b.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])



In [ ]:
with torch.inference_mode():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)

    loss = torch.sum(a + b)

    print(f'{loss=}')

    loss.backward()

loss=tensor(11.5306)


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
loss2 = torch.sum(a + b)

loss2

In [ ]:
@torch.no_grad()
def foo():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)

    loss = torch.mean(a + b)

    print(f'{loss=}')

    return a, b

In [ ]:
a, b = foo()

loss=tensor(0.8685)


In [ ]:
torch.mean(a - b)

tensor(-0.0716, grad_fn=<MeanBackward0>)

In [ ]:
@torch.inference_mode()
def foo():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)

    loss = torch.mean(a + b)

    print(f'{loss=}')

    return a, b

In [ ]:
a, b = foo()

loss=tensor(1.0267)


In [ ]:
torch.mean(a - b)

In [ ]:
a.requires_grad = False

## Полносвязные слои и функции активации в `PyTorch`

In [ ]:
from torch import nn

In [ ]:
import torch.nn as nn

### Полносвязный слой

>$y_j = \sum\limits_{i=1}^{n}x_iw_{ji} + b_j$


In [ ]:
layer = nn.Linear(in_features=5, out_features=3)

In [ ]:
layer

Linear(in_features=5, out_features=3, bias=True)

In [ ]:
layer.weight

Parameter containing:
tensor([[ 0.2954, -0.2540, -0.3949,  0.1980,  0.3619],
        [ 0.3240, -0.0350,  0.1800, -0.0339,  0.1654],
        [-0.0383,  0.3685, -0.4150,  0.3411, -0.3643]], requires_grad=True)

In [ ]:
layer.weight.shape

torch.Size([3, 5])

In [ ]:
layer.bias

Parameter containing:
tensor([-0.2384, -0.1925, -0.2777], requires_grad=True)

In [ ]:
layer.bias.shape

torch.Size([3])

In [ ]:
layer = nn.Linear(in_features=5, out_features=3, bias=False)

In [ ]:
layer.bias is None

True

In [ ]:
# layer.__call__

In [ ]:
x = torch.randn(5)

print(layer(x))

tensor([-0.3628, -0.9292,  0.3786], grad_fn=<SqueezeBackward4>)


In [ ]:
layer1 = nn.Linear(in_features=5, out_features=3)
layer2 = nn.Linear(in_features=3, out_features=1)

layer2(layer1(x))

tensor([0.4945], grad_fn=<ViewBackward0>)

### Функции активации

> Сигмоида $f(x) = \dfrac{1}{1 + e^{-x}}$

In [ ]:
activation = nn.Sigmoid()

In [ ]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([-0.7016,  0.6591, -0.4445, -0.8984,  0.5039])
tensor([0.3315, 0.6591, 0.3907, 0.2894, 0.6234])


> ReLU $f(x) = \max(0, x)$

In [ ]:
activation = nn.ReLU()

In [ ]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([ 0.8181, -1.0166,  1.8356,  1.0242, -0.7981])
tensor([0.8181, 0.0000, 1.8356, 1.0242, 0.0000])


> Leaky ReLU $f(x) = \max(0, x) + \alpha \min(0, x)$

In [ ]:
activation = nn.LeakyReLU(negative_slope=0.001)

In [ ]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([ 0.3847,  1.0362, -0.9832,  0.9055,  0.7440])
tensor([ 3.8466e-01,  1.0362e+00, -9.8321e-04,  9.0554e-01,  7.4396e-01])


In [ ]:
layer1 = nn.Linear(in_features=5, out_features=3)
activation = nn.LeakyReLU(negative_slope=0.001)
layer2 = nn.Linear(in_features=3, out_features=1)

layer2(activation(layer1(x)))

tensor([-0.1752], grad_fn=<ViewBackward0>)

## Градиентный спуск своими руками

In [ ]:
n_features = 2
n_objects = 300

torch.manual_seed(0)

w_true = torch.randn(n_features)
b_true = torch.randn(1)

x = (torch.rand(n_objects, n_features) - 0.5) * 10 * (torch.arange(n_features) * 2 + 1)
y = torch.matmul(x, w_true) + torch.randn(n_objects) + b_true

In [ ]:
x.shape

torch.Size([300, 2])

In [ ]:
y.shape

torch.Size([300])

In [ ]:
n_steps = 200
step_size = 1e-2

In [ ]:
w = torch.rand(n_features, requires_grad=True)
b = torch.rand(1, requires_grad=True)

for i in range(n_steps):
    y_pred = torch.matmul(x, w) + b

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

#     print(f'{w.grad=}\n')
#     print(f'{b.grad=}\n')

    with torch.no_grad():
        w -= w.grad * step_size
        b -= b.grad * step_size

    w.grad.zero_()
    b.grad.zero_()

MSE на шаге 1 23.65750
MSE на шаге 2 15.53605
MSE на шаге 3 12.11575
MSE на шаге 4 10.36995
MSE на шаге 5 9.30175
MSE на шаге 6 8.55659
MSE на шаге 7 7.99169
MSE на шаге 8 7.53972
MSE на шаге 9 7.16377
MSE на шаге 10 6.84131
MSE на шаге 11 6.55765
MSE на шаге 12 6.30292
MSE на шаге 13 6.07033
MSE на шаге 14 5.85515
MSE на шаге 15 5.65409
MSE на шаге 16 5.46478
MSE на шаге 17 5.28555
MSE на шаге 18 5.11514
MSE на шаге 19 4.95265
MSE на шаге 20 4.79736
MSE на шаге 21 4.64871
MSE на шаге 31 3.45555
MSE на шаге 41 2.65631
MSE на шаге 51 2.11964
MSE на шаге 61 1.75925
MSE на шаге 71 1.51724
MSE на шаге 81 1.35471
MSE на шаге 91 1.24558
MSE на шаге 101 1.17229
MSE на шаге 111 1.12307
MSE на шаге 121 1.09002
MSE на шаге 131 1.06782
MSE на шаге 141 1.05292
MSE на шаге 151 1.04291
MSE на шаге 161 1.03619
MSE на шаге 171 1.03168
MSE на шаге 181 1.02864
MSE на шаге 191 1.02661


In [ ]:
x.shape

torch.Size([300, 2])

In [ ]:
layer = nn.Linear(in_features=n_features, out_features=1)


for i in range(n_steps):
    y_pred = layer(x)

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

#     layer.weight.grad.zero_()
#     layer.bias.grad.zero_()

    layer.zero_grad()

MSE на шаге 1 67.76115
MSE на шаге 2 42.90441
MSE на шаге 3 34.78294
MSE на шаге 4 31.90576
MSE на шаге 5 30.72448
MSE на шаге 6 30.12742
MSE на шаге 7 29.75547
MSE на шаге 8 29.48539
MSE на шаге 9 29.27014
MSE на шаге 10 29.08891
MSE на шаге 11 28.93083
MSE на шаге 12 28.78951
MSE на шаге 13 28.66082
MSE на шаге 14 28.54199
MSE на шаге 15 28.43109
MSE на шаге 16 28.32677
MSE на шаге 17 28.22807
MSE на шаге 18 28.13428
MSE на шаге 19 28.04487
MSE на шаге 20 27.95945
MSE на шаге 21 27.87770
MSE на шаге 31 27.22173
MSE на шаге 41 26.78239
MSE на шаге 51 26.48738
MSE на шаге 61 26.28927
MSE на шаге 71 26.15623
MSE на шаге 81 26.06689
MSE на шаге 91 26.00690
MSE на шаге 101 25.96661
MSE на шаге 111 25.93955
MSE на шаге 121 25.92138
MSE на шаге 131 25.90918
MSE на шаге 141 25.90099
MSE на шаге 151 25.89549
MSE на шаге 161 25.89179
MSE на шаге 171 25.88931
MSE на шаге 181 25.88765
MSE на шаге 191 25.88653


In [ ]:
layer(x)

tensor([[-2.7298],
        [-2.7292],
        [-2.7318],
        [-2.7311],
        [-2.7278],
        [-2.7308],
        [-2.7292],
        [-2.7330],
        [-2.7296],
        [-2.7168],
        [-2.7313],
        [-2.7349],
        [-2.7305],
        [-2.7286],
        [-2.7363],
        [-2.7269],
        [-2.7251],
        [-2.7222],
        [-2.7308],
        [-2.7260],
        [-2.7310],
        [-2.7279],
        [-2.7256],
        [-2.7202],
        [-2.7229],
        [-2.7306],
        [-2.7265],
        [-2.7337],
        [-2.7233],
        [-2.7287],
        [-2.7279],
        [-2.7318],
        [-2.7289],
        [-2.7257],
        [-2.7223],
        [-2.7243],
        [-2.7390],
        [-2.7176],
        [-2.7257],
        [-2.7269],
        [-2.7223],
        [-2.7276],
        [-2.7244],
        [-2.7321],
        [-2.7252],
        [-2.7309],
        [-2.7242],
        [-2.7299],
        [-2.7348],
        [-2.7298],
        [-2.7290],
        [-2.7337],
        [-2.

In [ ]:
layer(x).shape

torch.Size([300, 1])

In [ ]:
y.shape

torch.Size([300])

In [ ]:
(layer(x) - y).shape

torch.Size([300, 300])

In [ ]:
layer(x).ravel().shape

torch.Size([300])

In [ ]:
(layer(x).ravel() - y).shape

torch.Size([300])

In [ ]:
layer = nn.Linear(in_features=n_features, out_features=1)

for i in range(n_steps):
    y_pred = layer(x).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

    layer.zero_grad()

MSE на шаге 1 82.40031
MSE на шаге 2 34.83058
MSE на шаге 3 18.67639
MSE на шаге 4 12.57786
MSE на шаге 5 9.87140
MSE на шаге 6 8.42349
MSE на шаге 7 7.51441
MSE на шаге 8 6.87739
MSE на шаге 9 6.39865
MSE на шаге 10 6.02125
MSE на шаге 11 5.71254
MSE на шаге 12 5.45201
MSE на шаге 13 5.22616
MSE на шаге 14 5.02584
MSE на шаге 15 4.84476
MSE на шаге 16 4.67857
MSE на шаге 17 4.52421
MSE на шаге 18 4.37955
MSE на шаге 19 4.24304
MSE на шаге 20 4.11358
MSE на шаге 21 3.99035
MSE на шаге 31 3.01138
MSE на шаге 41 2.35799
MSE на шаге 51 1.91931
MSE на шаге 61 1.62472
MSE на шаге 71 1.42689
MSE на шаге 81 1.29405
MSE на шаге 91 1.20484
MSE на шаге 101 1.14493
MSE на шаге 111 1.10470
MSE на шаге 121 1.07768
MSE на шаге 131 1.05954
MSE на шаге 141 1.04736
MSE на шаге 151 1.03917
MSE на шаге 161 1.03368
MSE на шаге 171 1.02999
MSE на шаге 181 1.02751
MSE на шаге 191 1.02585


In [ ]:
n_features = 5
n_objects = 300

torch.manual_seed(0)

w_true = torch.randn(n_features)

x = (torch.rand(n_objects, n_features) - 0.5) * 10 * (torch.arange(n_features) * 2 + 1)
y = torch.matmul(x, w_true) + torch.randn(n_objects)

In [ ]:
x.shape, y.shape

(torch.Size([300, 5]), torch.Size([300]))

In [ ]:
n_steps = 500
step_size = 1e-3

In [ ]:
layer = nn.Linear(in_features=n_features, out_features=1)

for i in range(n_steps):
    y_pred = layer(x).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 50 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

    layer.zero_grad()

MSE на шаге 1 1522.64282
MSE на шаге 2 345.22867
MSE на шаге 3 134.71323
MSE на шаге 4 69.14162
MSE на шаге 5 45.61798
MSE на шаге 6 36.15922
MSE на шаге 7 31.74179
MSE на шаге 8 29.24493
MSE на шаге 9 27.53952
MSE на шаге 10 26.19924
MSE на шаге 11 25.05364
MSE на шаге 12 24.02866
MSE на шаге 13 23.08827
MSE на шаге 14 22.21260
MSE на шаге 15 21.38941
MSE на шаге 16 20.61047
MSE на шаге 17 19.86992
MSE на шаге 18 19.16343
MSE на шаге 19 18.48770
MSE на шаге 20 17.84015
MSE на шаге 51 6.27401
MSE на шаге 101 1.74083
MSE на шаге 151 1.02593
MSE на шаге 201 0.91269
MSE на шаге 251 0.89435
MSE на шаге 301 0.89104
MSE на шаге 351 0.89019
MSE на шаге 401 0.88977
MSE на шаге 451 0.88948


In [ ]:
n_steps = 1000
step_size = 3e-4

In [ ]:
layer1 = nn.Linear(in_features=n_features, out_features=3)
layer2 = nn.Linear(in_features=3, out_features=1)
activation = nn.ReLU()


for i in range(n_steps):
    y_pred = layer2(activation(layer1(x))).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 50 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer1.weight -= layer1.weight.grad * step_size
        layer1.bias -= layer1.bias.grad * step_size
        layer2.weight -= layer2.weight.grad * step_size
        layer2.bias -= layer2.bias.grad * step_size

    layer1.zero_grad()
    layer2.zero_grad()

MSE на шаге 1 2065.53369
MSE на шаге 2 1941.40063
MSE на шаге 3 1890.73816
MSE на шаге 4 1863.17334
MSE на шаге 5 1843.74536
MSE на шаге 6 1825.21838
MSE на шаге 7 1803.15234
MSE на шаге 8 1775.96985
MSE на шаге 9 1741.44421
MSE на шаге 10 1696.50024
MSE на шаге 11 1638.66467
MSE на шаге 12 1570.60828
MSE на шаге 13 1498.17651
MSE на шаге 14 1426.69543
MSE на шаге 15 1361.06189
MSE на шаге 16 1304.04333
MSE на шаге 17 1252.44177
MSE на шаге 18 1201.12512
MSE на шаге 19 1142.44922
MSE на шаге 20 1069.69434
MSE на шаге 51 10.77816
MSE на шаге 101 5.31390
MSE на шаге 151 3.22006
MSE на шаге 201 2.08225
MSE на шаге 251 1.45981
MSE на шаге 301 1.16964
MSE на шаге 351 1.03444
MSE на шаге 401 0.97123
MSE на шаге 451 0.94166
MSE на шаге 501 0.92668
MSE на шаге 551 0.91742
MSE на шаге 601 0.91137
MSE на шаге 651 0.90724
MSE на шаге 701 0.90359
MSE на шаге 751 0.90093
MSE на шаге 801 0.89880
MSE на шаге 851 0.89742
MSE на шаге 901 0.89643
MSE на шаге 951 0.89556
